name: Deploy and Linting
on: [push, workflow_dispatch]
jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
            node-version: 18
      - name: Install Dependencies
        run: npm ci
      - name: Lint code
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    needs: linting
    steps:
      - name: Test the app
        run: npm run test-ci
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Build the app
        run: npm run build
      - name: Deploy the app
        run: echo 'Deploying...'

      