name: On Issues
on: 
  issues:
    types: [opened]
jobs:
  display_issue_info:
    runs-on: ubuntu-latest
    steps:
      - name: Display issue info
        run: echo "New issue ${{toJSON(github.event)}}"

