name: Matrix Demo
on: push
jobs:
  build:
    continue-on-error: true # To continue with the matrix execution even if some combination fails
    strategy: 
      matrix: # For running on different configurations
        node-version: [12, 14, 16]
        operating-system:  [ubuntu-latest, windows-latest]
        include: # To add single combinations to the list
          - node-version: 18 
            operating-system: ubuntu-latest
        exclude: 
          - node-version: 12
            operating-system: windows-latest
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Get the code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm ci
      - name: Build Project
        run: npm run build