name: Reusable Deploy
on: 
  workflow_call: # This workflow will be called inside other WF
    inputs: # To receive parameters
      artifact-name:
        description: The name of the deployable artifact
        required: true
        type: string
        default: dist
    outputs:
      result:
        description: Result of the deployment operation
        value: ${{ jobs.deploy.outputs.outcome }}
    secrets: # In case we need secrets
      some-secrets:
        required: false
jobs:
  deploy: 
    outputs: 
      outcome: ${{ steps.set-result.outputs.step-result}}
    runs-on: ubuntu-latest
    steps:
      - name: Get artifacts
        uses: actions/download-artifact
        with:
          name: ${{ inputs.artifact-name }}
      - name: List files
        run: ls
      - name: Output information
        run: echo "Deploying app!"
      - name: Set Result output
        id: set-result
        run: echo "step-result=success" >> $GITHUB_OUTPUT ";"